// ═══════════════════════════════════════════════════════════════════════════════
// English UI text — all user-visible strings centralized
// ═══════════════════════════════════════════════════════════════════════════════

export const uiTextEn = {
  combat: {
    title: "Wasteland Combat",
    fighting: "Fighting",
    stop: "Stop",
    attackInterval: "Attack Interval",
    health: "HP",
    enemyLabel: "Enemy",
    enemyHp: (name: string) => `👹 ${name}`,
    playerHp: "❤️ HP",
    attack: "Attack",
    dungeonEnter: "Explore",
    dungeonInProgress: "Raiding",
    towerTitle: "Abandoned Skyscraper",
    towerFloor: (n: number) => `Floor: ${n}`,
    towerButton: "Ascend Tower",
    trialTitle: "Radiation Trial",
    trialKey: (n: number) => `Keys: ${n}`,
    trialButton: "Enter Rad Zone",
    dungeonCost: (lvl: number, gold: number, bones?: number, dragonBones?: number) =>
      `⚔${lvl} 💰${gold}G${bones ? ` 🦴${bones}` : ""}${dragonBones ? ` 🐉${dragonBones}` : ""}`,
    statLife: "HP",
    statAttack: "ATK",
    statDefence: "DEF",
    statCombatLevel: "Combat Lv",
    combatLevel: (n: number) => `Combat Level ${n}`,
    weapon: (style: string) => `Weapon: ${style}`,
    tabEnemies: "Wasteland Creatures",
    tabDungeons: "Ruin Exploration",
    tabTower: "Tower Climb",
    tabTrial: "Radiation Trial",
    reqLevel: (n: number) => `Requires Combat Lv ${n}`,
    cannotEnter: "Cannot Enter",
    cannotFight: "Cannot Fight",
    stopFailed: "Stop Failed",
    strongAgainst: "Strong",
    weakTo: "Weak",
    bones: "Bones",
    dragonBones: "Dragon Bones",
    attackButton: "⚔️ Attack",
    stopButton: "Stop",
    xpLabel: "⭐ XP",
    lootLabel: (n: number) => `🎒 ${n} loot items`,
    pageSubtitle: (combatLevel: number, weaponStyle: string) => `Combat Lv ${combatLevel} · Weapon: ${weaponStyle}`,
    towerFloorActive: (n: number) => `Tower Floor ${n}`,
    trialWaveActive: (n: number) => `Trial Wave ${n}`,
    dungeonStatus: "Raiding",
    towerStatus: "Climbing",
    trialStatus: "Trialing",
    tabLabelEnemies: "Wasteland Creatures",
    tabLabelDungeons: "Ruin Exploration",
    tabLabelTower: "Tower Climb",
    tabLabelTrial: "Radiation Trial",
  },

  sidebar: {
    title: "Radiation Wasteland",
    version: "Radiation Wasteland v1.0",
    sectionGeneral: "General",
    sectionCombat: "Combat",
    sectionGathering: "Gathering",
    sectionProduction: "Production",
    sectionTech: "Tech",
    navDashboard: "Overview",
    navInventory: "Inventory",
    navGems: "Gems",
    navMaterials: "Materials",
    navShelter: "Shelter",
    navTown: "Survivor Camp",
    navTalents: "Talents",
    navPets: "Pets",
    navCombat: "Wasteland Combat",
    navDungeons: "Ruin Exploration",
    navTower: "Tower Climb",
    navTrial: "Radiation Trial",
    navWoodcutting: "Woodcutting",
    navMining: "Mining",
    navSmelting: "Smelting",
    navFishing: "Fishing",
    navHunting: "Hunting",
    navThieving: "Scavenging",
    navCrafting: "Crafting",
    navAgility: "Agility",
    navExploration: "Exploration",
    navSmithing: "Smithing",
    navLeatherworking: "Leatherworking",
    navJewelcrafting: "Jewelcrafting",
    navTools: "Tool Crafting",
    navEquipmentSynth: "Equipment Synth",
    navCooking: "Cooking",
    navAlchemy: "Alchemy",
    navPrayer: "Prayers",
    navWastelandTech: "Wasteland Tech",
    navBounties: "Bounties",
    navGamble: "Gamble",
  },

  dashboard: {
    title: "Radiation Wasteland Overview",
    subtitle: "Survive the wasteland",
    gatheringSkills: "Gathering Skills",
    combatSkills: "Combat Skills",
    level: "Level",
    progress: "Progress",
    totalXp: "Total XP",
    active: "Active",
    stopAll: "Stop",
    combatLevel: "Combat Level",
    gold: "Caps",
    smithingLevel: "Smithing Lv",
    exportTitle: "Export Save",
    importTitle: "Import Save",
    importSuccess: "Save imported! Refresh to apply.",
    importFail: "Import Failed",
    smithing: "Smithing",
    combatAttack: "Attack",
    combatDefence: "Defence",
    combatHitpoints: "Hitpoints",
    combatRanged: "Ranged",
    combatMagic: "Magic",
    wastelandTipTitle: "Wasteland Survival Tips",
    switchTier: "Switch Tier →",
    activeAction: (action: string) => `${action.replace(/_/g, " ")} active`,
    shelterTitle: "Shelter Core",
    manageShelter: "Manage shelter →",
    buildable: "Build",
    buildingLocked: (tier: number) => `Requires World Tier ${tier}`,
    terminalTitle: "ACTION.SYS",
    terminalStatus: "STATUS:",
    terminalIdle: "> SYSTEM READY — no active task",
    terminalHint: "> Select scavenge, combat, or craft to begin",
    terminalRunning: "> Task in progress…",
    terminalEta: (sec: string) => `> ETA: ${sec}s`,
    scavengeSkills: "Scavenge Ops",
    scavengeZone: "Scavenge Front",
  },

  shell: {
    zoneNavTitle: "Zone Nav",
    mobileNavTitle: "Wasteland Terminal",
    dockTitle: "Quick zones",
    openNav: "Open navigation",
    radiation: "Radiation",
    temperature: "Temperature",
    lootBag: "Loot",
    zones: {
      camp: "Camp",
      scavenge: "Scavenge",
      wasteland: "Combat",
      workshop: "Workshop",
      stash: "Stash",
      frontier: "Frontier",
    },
  },

  header: {
    idle: "Idle — No active task",
    stop: "Stop",
    combat: "Combat",
    dungeon: "Dungeon",
    tower: "Tower Climb",
    trial: "Radiation Trial",
    thieving: "Scavenge",
    skills: {
      woodcutting: "Woodcutting", mining: "Mining", smelting: "Smelting",
      fishing: "Fishing", hunting: "Hunting", thieving: "Scavenging",
      smith: "Smithing", leather: "Leatherworking", jewel: "Jewelcrafting", tool: "Tool Crafting",
      agility: "Agility", exploration: "Exploration", crafting: "Crafting",
      cooking: "Cooking", alchemy: "Alchemy", prayer: "Prayers",
    } as Record<string, string>,
  },

  skillPage: {
    xpProgress: "XP Progress",
    gatheringResources: "Gathering Resources",
    activeTitle: "Currently Active",
    levelLocked: (n: number) => `Level ${n}`,
    owned: (n: number) => `Owned: ${n}`,
    stop: "Stop",
    start: "Start",
    activeBadge: "Active",
    subtitle: (level: number, xp: string) => `Level ${level} · ${xp} XP`,
    xpToLevel: (current: string, next: string, nextLevel: number) => `${current} / ${next} XP → Lv ${nextLevel}`,
    timeSeconds: (t: number) => `⏱ ${t}s`,
    xpGain: (xp: number) => `⭐ ${xp} XP`,
    lockedLabel: (n: number) => `🔒 Lv ${n}`,
    resourceOwned: (n: string) => `📦 ${n} owned`,
  },

  wasteland: {
    survivalTips: [
      "A water purifier is your most important gear — rad-water kills in three days.",
      "Wasteland traders don't take currency. Bring extra ammo and medicine.",
      "Night in the wastes is ten times deadlier. Mutants grow bolder in darkness.",
      "Thicker shelter walls save lives. Radiation storms strike without warning.",
      "Never trust anyone claiming to be from the 'Restoration Government'. They're gone.",
      "Bones fuel prayer rituals. Don't waste them.",
      "Dragon bones are the rarest material — only the mightiest creatures drop them.",
      "Smithing is the core survival skill. A good weapon beats a crate of canned food.",
      "Mutant meat is edible — but cook it first. Raw meat gives you radiation sickness.",
      "Outposts gather resources automatically. Place them in key zones.",
      "Higher world tiers mean richer resources — and deadlier enemies. Choose wisely.",
      "Save often. The wasteland doesn't give second chances.",
    ],
    townLevels: {
      0: "Barren Wasteland — not even a tent",
      5: "Small Camp — survivors begin to gather",
      15: "Settlement — basic water and defenses established",
      30: "Outpost Town — traders and travelers appear",
      50: "Vault City — the last beacon of civilization in the wastes",
    },
  },
  pages: {
    thieving: {
      title: "Thieving", stealth: "Stealth", stealthSkill: "Stealth Ability", activeTarget: "Pickpocketing",
      stop: "Stop", selectTarget: "Select Target", hidden: "Hidden", noHidden: "No hidden targets unlocked",
      perception: "Perception", goldPer: "Caps", xpPer: "XP/Attempt", interval: "Interval",
      successRate: "Success Rate", doubleRate: "Double Rate",
      goldPerAttempt: (n: number) => `~${n} caps/attempt`,
      uniqueUnlock: "Unlock to steal unique equipment", steal: "Steal", level: "Level",
    },
    homestead: {
      title: "Homestead", furnace: "Furnace",
      warmth: { warm: "Warm", cool: "Cool", cold: "Cold", freezing: "Freezing", frozen: "Frozen" } as Record<string, string>,
      buildSuccess: "Build successful", buildFail: "Build failed", addFail: "Add failed",
      warningFrozen: "⚠️ Freezing! Speed greatly reduced, losing HP",
      warningCold: "❄️ Cold, speed reduced", warningCool: "🌬️ Cool, speed slightly reduced",
      totalBonuses: "Total Bonuses", noBonuses: "No building bonuses",
      sectionGeneral: "🏠 General", sectionTech: "⚙️ Wasteland Tech", sectionWonders: "🏛️ Wonders",
      farm: "Farm", plant: "Plant", harvestReady: "Ready to harvest",
      plantSuccess: "Planted",
      plantFail: "Plant failed", harvestSuccess: "Harvest successful", harvestFail: "Harvest failed",
      build: "Build", upgrade: "Upgrade", maxLevel: "Max", locked: "🔒 Locked",
    },
    town: {
      title: "Town", townLevel: (n: number) => `Town Level: ${n}`,
      operateSuccess: "Success", operateFail: "Failed", npcLeft: "NPC has left",
      campMembers: "Camp Members", sendAway: "Dismiss",
      gambleMerchant: "Wasteland Merchant — Blood Shard Gambling", gamble: "Gamble",
      bloodShards: "Blood Shards:", shardPerKill: "2 shards per enemy kill",
      knownTravelers: "Known Travelers", reqTownLevel: "Requires town level", reqDungeon: "Requires dungeon clear",
      noVisitors: "No travelers passing by…",
      attractHint: "Keep building to attract NPCs at town level 5",
      attractHint2: "Travelers occasionally pass through your settlement",
    },
    talents: {
      title: "Talent Tree", available: "Available", used: "Used", remaining: "Remaining", reset: "Reset",
      unlocked: "Unlocked", canUnlock: "Available",
      unlockSuccess: "Talent unlocked", unlockFail: "Unlock failed",
      resetSuccess: "Talents reset", resetFail: "Reset failed",
      resetConfirm: "Reset all talent points? This cannot be undone.",
      styleMelee: "Melee", styleRanged: "Ranged", styleMagic: "Magic",
      centerUnlock: (skill: string) => `${skill} Lv 15 auto-unlocks center`,
    },
    gems: {
      title: "Gems", inventory: "Gem Inventory", empty: "No gems",
      emptyHint: "Mine or defeat enemies to obtain gems!",
      socket: "Socket", equippedItems: "Equipped Items", selectGem: "Select a gem to socket:",
      noGems: "You have no gems. Go mining or fight!", allFilled: "All gem sockets filled!",
      noItems: "No socketable items. Defeat enemies or craft rare+ items for sockets.",
      dropGuide: "Gem Drop Guide", synth: "Gem Synthesis",
      synthRule: "5 same quality → 1 upgrade (100%) · 3 (25%) · 4 (50%) · costs gold",
      synthSuccess: "Synthesis successful", combatDrop: "⚔️ Combat", miningDrop: "⛏️ Mining",
    },
    crafting: {
      smithing: "Smithing", leatherworking: "Leatherworking", jewelcrafting: "Jewelcrafting",
      cooking: "Cooking", alchemy: "Alchemy", prayer: "Prayers",
      activeCraft: (name: string) => `Crafting ${name}`, stop: "Stop",
      recipe: "Recipes", crafting_: "Crafting...", reqSmithingLevel: "Requires Smithing Lv",
      craft: "Craft", levelSuffix: (n: number) => `Lv ${n}`, available: "Available Hides",
      materials: "Materials:", owned: "Owned:", ownLabel: "Owned", making: "Materials",
      craftComplete: "Craft complete", craftFail: "Craft failed", notEnough: "Not enough materials",
      cookingComplete: "Cooking complete", cookingFail: "Cooking failed",
      alchemyComplete: "Alchemy complete", alchemyFail: "Alchemy failed",
      bones: "Bones:", dragonBones: "Dragon Bones:",
    },
  },
} as const;
