// ═══════════════════════════════════════════════════════════════════════════════
// 统一 UI 文案 — 所有用户可见文本集中管理
// ═══════════════════════════════════════════════════════════════════════════════

export const uiText = {
  combat: {
    title: "废土战斗",
    fighting: "战斗中",
    stop: "停止",
    attackInterval: "攻击间隔",
    health: "生命",
    enemyLabel: "敌人",
    enemyHp: (name: string) => `👹 ${name}`,
    playerHp: "❤️ 生命",
    attack: "进攻",
    dungeonEnter: "探索",
    dungeonInProgress: "攻略中",
    towerTitle: "废弃摩天楼",
    towerFloor: (n: number) => `当前楼层: ${n}`,
    towerButton: "攀登高塔",
    trialTitle: "辐射试炼",
    trialKey: (n: number) => `钥匙: ${n}`,
    trialButton: "进入辐射区",
    dungeonCost: (lvl: number, gold: number, bones?: number, dragonBones?: number) =>
      `⚔${lvl} 💰${gold}G${bones ? ` 🦴${bones}` : ""}${dragonBones ? ` 🐉${dragonBones}` : ""}`,
    statLife: "生命",
    statAttack: "攻击",
    statDefence: "防御",
    statCombatLevel: "战斗等级",
    combatLevel: (n: number) => `战斗等级 ${n}`,
    weapon: (style: string) => `武器: ${style}`,
    tabEnemies: "废土生物",
    tabDungeons: "废墟探索",
    tabTower: "高塔攀登",
    tabTrial: "辐射试炼",
    reqLevel: (n: number) => `需要战斗等级 ${n}`,
    cannotEnter: "无法进入",
    cannotFight: "无法战斗",
    stopFailed: "停止失败",
  },

  sidebar: {
    title: "辐射废土",
    version: "辐射废土 v1.0",
    sectionGeneral: "常规",
    sectionCombat: "战斗",
    sectionGathering: "采集",
    sectionProduction: "生产",
    sectionTech: "科技",
    navDashboard: "总览",
    navInventory: "背包",
    navGems: "宝石",
    navHomestead: "避难所",
    navTown: "幸存者营地",
    navTalents: "天赋",
    navCombat: "废土战斗",
    navDungeons: "废墟探索",
    navTower: "高塔攀登",
    navTrial: "辐射试炼",
    navWoodcutting: "伐木",
    navMining: "采矿",
    navSmelting: "冶炼",
    navFishing: "钓鱼",
    navHunting: "狩猎",
    navThieving: "搜刮",
    navAgility: "敏捷",
    navExploration: "探索",
    navSmithing: "锻造",
    navLeatherworking: "皮革制作",
    navJewelcrafting: "珠宝制作",
    navTools: "工具制作",
    navEquipmentSynth: "装备合成",
    navCooking: "烹饪",
    navAlchemy: "炼金",
    navPrayer: "祷言",
    navWastelandTech: "废土科技",
  },

  dashboard: {
    title: "辐射废土总览",
    subtitle: "在废土中生存下去",
    gatheringSkills: "采集技能",
    combatSkills: "战斗技能",
    level: "等级",
    progress: "进度",
    totalXp: "总经验",
    active: "进行中",
    stopAll: "停止",
    combatLevel: "战斗等级",
    gold: "金币",
    smithingLevel: "锻造等级",
    exportTitle: "存档导出中…",
    importSuccess: "存档导入成功！刷新页面生效",
    importFail: "导入失败",
  },

  skillPage: {
    xpProgress: "经验进度",
    gatheringResources: "采集资源",
    activeTitle: "当前进行中",
    levelLocked: (n: number) => `等级 ${n}`,
    owned: (n: number) => `持有 ${n}`,
    stop: "停止",
    start: "开始",
  },

  shared: {
    gold: "💰",
    bones: "🦴",
    dragonBones: "🐉",
    hp: "❤️",
    attack: "⚔️",
    defence: "🛡️",
    xp: "⭐",
    time: "⏱",
  },

  // ═══ Wasteland flavor / atmosphere ═══════════════════════════════════════
  wasteland: {
    zoneDescriptions: {
      deadwood: "枯死的树木扭曲成诡异的形状，辐射雨从龟裂的树皮间滴落。远处传来变异生物的嚎叫。",
      gasStation: "废弃加油站的油泵早已锈蚀，地面上残留着干涸的黑色油渍。有人在这里留下了一些物资。",
      ruinTown: "曾经繁华的小镇如今只剩断壁残垣。倒塌的墙壁上还能看到核爆前的广告牌。",
      radSwamp: "辐射污染让沼泽散发着诡异的绿色荧光。每一步都要小心——泥浆下可能藏着什么。",
      brokenRoad: "破碎的公路延伸到地平线，路面被核爆冲击波撕裂成巨大的板块。路边散落着废弃车辆。",
      abandonedFarm: "农场已经荒废多年，变异的巨型昆虫在曾经的农田里筑巢。谷仓里也许还有完好的工具。",
      bunker: "地下掩体的铁门半开着，里面漆黑一片。墙壁上的应急灯还在微弱地闪烁。",
      acidPlain: "酸雨将平原腐蚀得千疮百孔，空气中弥漫着刺鼻的化学气味。只有最顽强的生物能在这里生存。",
      sandWaste: "沙暴遮蔽了天空，能见度不到十米。废弃的军事设施半埋在沙丘之下。",
      snowRuin: "核冬天让这片废墟永远被冰雪覆盖。废弃的研究站里可能保存着战前科技。",
    },
    survivalTips: [
      "净水器是你最重要的装备——辐射水能在三天内杀死你。",
      "废土商人不接受货币，他们只换物资。带上多余的弹药和药品。",
      "夜晚的废土比白天危险十倍。变异生物在黑暗中更加活跃。",
      "避难所的墙壁越厚越好——辐射风暴随时可能来袭。",
      "不要相信任何自称「政府重建委员会」的人。政府早在核爆中消失了。",
      "骨头可以用于祷言仪式。不要浪费它们。",
      "龙骨是最珍贵的材料——只有最强大的生物才会掉落。",
      "锻造是废土生存的核心技能。一把好武器比一箱罐头更有价值。",
      "变异生物的肉可以吃，但必须先烹饪。生吃会让你染上辐射病。",
      "前哨站能自动采集资源。在关键区域建立前哨站是明智的选择。",
      "世界层级越高，资源越丰富——但敌人也更强大。量力而行。",
      "记得经常存档。废土不会给你第二次机会。",
    ],
    townLevels: {
      0: "荒芜之地 — 连一个帐篷都没有",
      5: "小营地 — 幸存者开始聚集",
      15: "定居点 — 有了基本的水源和防御",
      30: "前哨镇 — 商人和旅人开始出现",
      50: "避难所都市 — 废土中最后的文明之光",
    },
  },
} as const;

export type UIText = typeof uiText;
