// ═══════════════════════════════════════════════════════════════════════════════
// English UI text — all user-visible strings centralized
// ═══════════════════════════════════════════════════════════════════════════════

export const uiTextEn = {
  combat: {
    title: "Wasteland Combat",
    fighting: "Fighting",
    stop: "Stop",
    attackInterval: "Attack Interval",
    health: "HP",
    enemyLabel: "Enemy",
    enemyHp: (name: string) => `👹 ${name}`,
    playerHp: "❤️ HP",
    attack: "Attack",
    dungeonEnter: "Explore",
    dungeonInProgress: "Raiding",
    towerTitle: "Abandoned Skyscraper",
    towerFloor: (n: number) => `Floor: ${n}`,
    towerButton: "Ascend Tower",
    trialTitle: "Radiation Trial",
    trialKey: (n: number) => `Keys: ${n}`,
    trialButton: "Enter Rad Zone",
    dungeonCost: (lvl: number, gold: number, bones?: number, dragonBones?: number) =>
      `⚔${lvl} 💰${gold}G${bones ? ` 🦴${bones}` : ""}${dragonBones ? ` 🐉${dragonBones}` : ""}`,
    statLife: "HP",
    statAttack: "ATK",
    statDefence: "DEF",
    statCombatLevel: "Combat Lv",
    combatLevel: (n: number) => `Combat Level ${n}`,
    weapon: (style: string) => `Weapon: ${style}`,
    tabEnemies: "Wasteland Creatures",
    tabDungeons: "Ruin Exploration",
    tabTower: "Tower Climb",
    tabTrial: "Radiation Trial",
    reqLevel: (n: number) => `Requires Combat Lv ${n}`,
    cannotEnter: "Cannot Enter",
    cannotFight: "Cannot Fight",
    stopFailed: "Stop Failed",
  },

  sidebar: {
    title: "Radiation Wasteland",
    version: "Radiation Wasteland v1.0",
    sectionGeneral: "General",
    sectionCombat: "Combat",
    sectionGathering: "Gathering",
    sectionProduction: "Production",
    sectionTech: "Tech",
    navDashboard: "Overview",
    navInventory: "Inventory",
    navGems: "Gems",
    navHomestead: "Shelter",
    navTown: "Survivor Camp",
    navTalents: "Talents",
    navCombat: "Wasteland Combat",
    navDungeons: "Ruin Exploration",
    navTower: "Tower Climb",
    navTrial: "Radiation Trial",
    navWoodcutting: "Woodcutting",
    navMining: "Mining",
    navSmelting: "Smelting",
    navFishing: "Fishing",
    navHunting: "Hunting",
    navThieving: "Scavenging",
    navAgility: "Agility",
    navExploration: "Exploration",
    navSmithing: "Smithing",
    navLeatherworking: "Leatherworking",
    navJewelcrafting: "Jewelcrafting",
    navTools: "Tool Crafting",
    navEquipmentSynth: "Equipment Synth",
    navCooking: "Cooking",
    navAlchemy: "Alchemy",
    navPrayer: "Prayers",
    navWastelandTech: "Wasteland Tech",
  },

  dashboard: {
    title: "Radiation Wasteland Overview",
    subtitle: "Survive the wasteland",
    gatheringSkills: "Gathering Skills",
    combatSkills: "Combat Skills",
    level: "Level",
    progress: "Progress",
    totalXp: "Total XP",
    active: "Active",
    stopAll: "Stop",
    combatLevel: "Combat Level",
    gold: "Gold",
    smithingLevel: "Smithing Lv",
    exportTitle: "Export Save",
    importSuccess: "Save imported! Refresh to apply.",
    importFail: "Import Failed",
  },

  skillPage: {
    xpProgress: "XP Progress",
    gatheringResources: "Gathering Resources",
    activeTitle: "Currently Active",
    levelLocked: (n: number) => `Level ${n}`,
    owned: (n: number) => `Owned: ${n}`,
    stop: "Stop",
    start: "Start",
  },

  shared: {
    gold: "💰",
    bones: "🦴",
    dragonBones: "🐉",
    hp: "❤️",
    attack: "⚔️",
    defence: "🛡️",
    xp: "⭐",
    time: "⏱",
  },

  wasteland: {
    zoneDescriptions: {
      deadwood: "Twisted dead trees creak under radioactive rain. Mutant howls echo in the distance.",
      gasStation: "Rusted fuel pumps stand silent over dried oil stains. Someone left supplies behind.",
      ruinTown: "Crumbled walls and faded billboards — all that remains of a once-bustling town.",
      radSwamp: "Toxic green glow seeps from the marsh. Every step could be your last.",
      brokenRoad: "The shattered highway stretches to the horizon, torn apart by the blast wave.",
      abandonedFarm: "Giant mutant insects have claimed the fields. The barn might still hold usable tools.",
      bunker: "The iron hatch hangs half-open. Emergency lights flicker weakly inside.",
      acidPlain: "Acid rain has pitted the landscape. The air burns with chemical stench.",
      sandWaste: "Sandstorms blot out the sky. Military ruins lie half-buried beneath the dunes.",
      snowRuin: "Nuclear winter has entombed these ruins in ice. Pre-war tech may lie within.",
    },
    survivalTips: [
      "A water purifier is your most important gear — rad-water kills in three days.",
      "Wasteland traders don't take currency. Bring extra ammo and medicine.",
      "Night in the wastes is ten times deadlier. Mutants grow bolder in darkness.",
      "Thicker shelter walls save lives. Radiation storms strike without warning.",
      "Never trust anyone claiming to be from the 'Restoration Government'. They're gone.",
      "Bones fuel prayer rituals. Don't waste them.",
      "Dragon bones are the rarest material — only the mightiest creatures drop them.",
      "Smithing is the core survival skill. A good weapon beats a crate of canned food.",
      "Mutant meat is edible — but cook it first. Raw meat gives you radiation sickness.",
      "Outposts gather resources automatically. Place them in key zones.",
      "Higher world tiers mean richer resources — and deadlier enemies. Choose wisely.",
      "Save often. The wasteland doesn't give second chances.",
    ],
    townLevels: {
      0: "Barren Wasteland — not even a tent",
      5: "Small Camp — survivors begin to gather",
      15: "Settlement — basic water and defenses established",
      30: "Outpost Town — traders and travelers appear",
      50: "Vault City — the last beacon of civilization in the wastes",
    },
  },
} as const;
