// ═══════════════════════════════════════════════════════════════════════════════
// 统一 UI 文案 — 所有用户可见文本集中管理
// ═══════════════════════════════════════════════════════════════════════════════

export const uiText = {
  combat: {
    title: "废土战斗",
    fighting: "战斗中",
    stop: "停止",
    attackInterval: "攻击间隔",
    health: "生命",
    enemyLabel: "敌人",
    enemyHp: (name: string) => `👹 ${name}`,
    playerHp: "❤️ 生命",
    attack: "进攻",
    dungeonEnter: "探索",
    dungeonInProgress: "攻略中",
    towerTitle: "废弃摩天楼",
    towerFloor: (n: number) => `当前楼层: ${n}`,
    towerButton: "攀登高塔",
    trialTitle: "辐射试炼",
    trialKey: (n: number) => `钥匙: ${n}`,
    trialButton: "进入辐射区",
    dungeonCost: (lvl: number, gold: number, bones?: number, dragonBones?: number) =>
      `⚔${lvl} 💰${gold}G${bones ? ` 🦴${bones}` : ""}${dragonBones ? ` 🐉${dragonBones}` : ""}`,
    statLife: "生命",
    statAttack: "攻击",
    statDefence: "防御",
    statCombatLevel: "战斗等级",
    combatLevel: (n: number) => `战斗等级 ${n}`,
    weapon: (style: string) => `武器: ${style}`,
    tabEnemies: "废土生物",
    tabDungeons: "废墟探索",
    tabTower: "高塔攀登",
    tabTrial: "辐射试炼",
    reqLevel: (n: number) => `需要战斗等级 ${n}`,
    cannotEnter: "无法进入",
    cannotFight: "无法战斗",
    stopFailed: "停止失败",
    strongAgainst: "克制",
    weakTo: "被克",
    // Additional labels used in combat.tsx
    bones: "骨头",
    dragonBones: "龙骨",
    attackButton: "⚔️ 进攻",
    stopButton: "停止",
    xpLabel: "⭐ XP",
    lootLabel: (n: number) => `🎒 战利品 ${n} 件`,
    pageSubtitle: (combatLevel: number, weaponStyle: string) => `战斗等级 ${combatLevel} · 武器: ${weaponStyle}`,
    towerFloorActive: (n: number) => `高塔第${n}层`,
    trialWaveActive: (n: number) => `试炼第${n}波`,
    dungeonStatus: "副本中",
    towerStatus: "高塔中",
    trialStatus: "试炼中",
    // Tab labels (used in tab bar)
    tabLabelEnemies: "废土生物",
    tabLabelDungeons: "废墟探索",
    tabLabelTower: "高塔攀登",
    tabLabelTrial: "辐射试炼",
  },

  sidebar: {
    title: "辐射废土",
    version: "辐射废土 v1.0",
    sectionGeneral: "常规",
    sectionCombat: "战斗",
    sectionGathering: "采集",
    sectionProduction: "生产",
    sectionTech: "科技",
    navDashboard: "总览",
    navInventory: "背包",
    navGems: "宝石",
    navMaterials: "材料",
    navShelter: "避难所",
    navTown: "幸存者营地",
    navTalents: "天赋",
    navPets: "成就",
    navCombat: "废土战斗",
    navDungeons: "废墟探索",
    navTower: "高塔攀登",
    navTrial: "辐射试炼",
    navWoodcutting: "伐木",
    navMining: "采矿",
    navSmelting: "冶炼",
    navFishing: "钓鱼",
    navHunting: "狩猎",
    navThieving: "搜刮",
    navCrafting: "制作",
    navAgility: "敏捷",
    navExploration: "探索",
    navSmithing: "锻造",
    navLeatherworking: "皮革制作",
    navJewelcrafting: "珠宝制作",
    navTools: "工具制作",
    navEquipmentSynth: "装备合成",
    navCooking: "烹饪",
    navAlchemy: "炼金",
    navPrayer: "祷言",
    navWastelandTech: "废土科技",
    navBounties: "悬赏任务",
  },

  dashboard: {
    title: "辐射废土总览",
    subtitle: "在废土中生存下去",
    gatheringSkills: "采集技能",
    combatSkills: "战斗技能",
    level: "等级",
    progress: "进度",
    totalXp: "总经验",
    active: "进行中",
    stopAll: "停止",
    combatLevel: "战斗等级",
    gold: "瓶盖",
    smithingLevel: "锻造等级",
    exportTitle: "存档导出中…",
    importTitle: "导入存档",
    importSuccess: "存档导入成功！刷新页面生效",
    importFail: "导入失败",
    smithing: "锻造",
    combatAttack: "攻击",
    combatDefence: "防御",
    combatHitpoints: "生命",
    combatRanged: "远程",
    combatMagic: "能量",
    wastelandTipTitle: "废土生存法则",
    switchTier: "切换层级 →",
    activeAction: (action: string) => `${action.replace(/_/g, " ")} 进行中`,
    shelterTitle: "避难所核心舱",
    manageShelter: "管理避难所 →",
    buildable: "可建造",
    buildingLocked: (tier: number) => `需要世界层级 ${tier}`,
    terminalTitle: "ACTION.SYS",
    terminalStatus: "STATUS:",
    terminalIdle: "> SYSTEM READY — 无任务运行",
    terminalHint: "> 选择拾荒、战斗或生产任务以开始",
    terminalRunning: "> 任务执行中…",
    terminalEta: (sec: string) => `> ETA: ${sec}s`,
    scavengeSkills: "外出拾荒",
    scavengeZone: "拾荒前线",
  },

  shell: {
    zoneNavTitle: "区域导航",
    mobileNavTitle: "废土终端",
    dockTitle: "快捷区域",
    openNav: "打开导航",
    radiation: "辐射",
    temperature: "温度",
    lootBag: "战利品",
    zones: {
      camp: "营地",
      scavenge: "拾荒",
      wasteland: "战斗",
      workshop: "工坊",
      stash: "物资",
      frontier: "远域",
    },
  },

  header: {
    idle: "空闲 — 无任务运行",
    stop: "停止",
    combat: "战斗",
    dungeon: "副本探索",
    tower: "高塔攀登",
    trial: "辐射试炼",
    thieving: "搜刮",
    skills: {
      woodcutting: "伐木", mining: "采矿", smelting: "冶炼",
      fishing: "钓鱼", hunting: "狩猎", thieving: "搜刮",
      smith: "锻造", leather: "皮革制作", jewel: "珠宝制作", tool: "工具制作",
      agility: "敏捷训练", exploration: "探索", crafting: "制作",
      cooking: "烹饪", alchemy: "炼金", prayer: "祷言",
    } as Record<string, string>,
  },

  skillPage: {
    xpProgress: "经验进度",
    gatheringResources: "采集资源",
    activeTitle: "当前进行中",
    levelLocked: (n: number) => `等级 ${n}`,
    owned: (n: number) => `持有 ${n}`,
    stop: "停止",
    start: "开始",
    activeBadge: "进行中",
    subtitle: (level: number, xp: string) => `等级 ${level} · 经验 ${xp}`,
    xpToLevel: (current: string, next: string, nextLevel: number) => `${current} / ${next} 经验 → ${nextLevel} 级`,
    timeSeconds: (t: number) => `⏱ ${t}s`,
    xpGain: (xp: number) => `⭐ ${xp} 经验`,
    lockedLabel: (n: number) => `🔒 ${n}级`,
    resourceOwned: (n: string) => `📦 持有 ${n}`,
  },

  shared: {
    gold: "💰",
    bones: "🦴",
    dragonBones: "🐉",
    hp: "❤️",
    attack: "⚔️",
    defence: "🛡️",
    xp: "⭐",
    time: "⏱",
  },

  // ═══ Wasteland flavor / atmosphere ═══════════════════════════════════════
  wasteland: {
    zoneDescriptions: {
      deadwood: "枯死的树木扭曲成诡异的形状，辐射雨从龟裂的树皮间滴落。远处传来变异生物的嚎叫。",
      gasStation: "废弃加油站的油泵早已锈蚀，地面上残留着干涸的黑色油渍。有人在这里留下了一些物资。",
      ruinTown: "曾经繁华的小镇如今只剩断壁残垣。倒塌的墙壁上还能看到核爆前的广告牌。",
      radSwamp: "辐射污染让沼泽散发着诡异的绿色荧光。每一步都要小心——泥浆下可能藏着什么。",
      brokenRoad: "破碎的公路延伸到地平线，路面被核爆冲击波撕裂成巨大的板块。路边散落着废弃车辆。",
      abandonedFarm: "农场已经荒废多年，变异的巨型昆虫在曾经的农田里筑巢。谷仓里也许还有完好的工具。",
      bunker: "地下掩体的铁门半开着，里面漆黑一片。墙壁上的应急灯还在微弱地闪烁。",
      acidPlain: "酸雨将平原腐蚀得千疮百孔，空气中弥漫着刺鼻的化学气味。只有最顽强的生物能在这里生存。",
      sandWaste: "沙暴遮蔽了天空，能见度不到十米。废弃的军事设施半埋在沙丘之下。",
      snowRuin: "核冬天让这片废墟永远被冰雪覆盖。废弃的研究站里可能保存着战前科技。",
    },
    survivalTips: [
      "净水器是你最重要的装备——辐射水能在三天内杀死你。",
      "废土商人不接受货币，他们只换物资。带上多余的弹药和药品。",
      "夜晚的废土比白天危险十倍。变异生物在黑暗中更加活跃。",
      "避难所的墙壁越厚越好——辐射风暴随时可能来袭。",
      "不要相信任何自称「政府重建委员会」的人。政府早在核爆中消失了。",
      "骨头可以用于祷言仪式。不要浪费它们。",
      "龙骨是最珍贵的材料——只有最强大的生物才会掉落。",
      "锻造是废土生存的核心技能。一把好武器比一箱罐头更有价值。",
      "变异生物的肉可以吃，但必须先烹饪。生吃会让你染上辐射病。",
      "前哨站能自动采集资源。在关键区域建立前哨站是明智的选择。",
      "世界层级越高，资源越丰富——但敌人也更强大。量力而行。",
      "记得经常存档。废土不会给你第二次机会。",
    ],
    townLevels: {
      0: "荒芜之地 — 连一个帐篷都没有",
      5: "小营地 — 幸存者开始聚集",
      15: "定居点 — 有了基本的水源和防御",
      30: "前哨镇 — 商人和旅人开始出现",
      50: "避难所都市 — 废土中最后的文明之光",
    },
  },
  pages: {
    thieving: {
      title: "盗窃",
      stealth: "潜行值",
      stealthSkill: "潜行能力",
      activeTarget: "正在偷窃",
      stop: "停止",
      selectTarget: "选择目标",
      hidden: "隐藏",
      noHidden: "未解锁隐藏目标",
      perception: "感知",
      goldPer: "瓶盖",
      xpPer: "经验/次",
      interval: "间隔",
      successRate: "成功率",
      doubleRate: "翻倍率",
      goldPerAttempt: (n: number) => `~${n}金/次`,
      uniqueUnlock: "解锁后可偷窃独特装备",
      steal: "偷窃",
      level: "等级",
    },
    homestead: {
      title: "家园",
      furnace: "火炉",
      warmth: {
        warm: "温暖", cool: "微凉", cold: "寒冷", freezing: "严寒", frozen: "冰冻",
      } as Record<string, string>,
      buildSuccess: "建造成功",
      buildFail: "建造失败",
      addFail: "添加失败",
      warningFrozen: "⚠️ 严寒！速度大幅降低，生命持续流失",
      warningCold: "❄️ 寒冷，速度降低",
      warningCool: "🌬️ 微凉，速度略微降低",
      totalBonuses: "家园总加成",
      noBonuses: "暂无建筑加成",
      sectionGeneral: "🏠 常规建筑",
      sectionTech: "⚙️ 废土科技",
      sectionWonders: "🏛️ 奇观",
      farm: "农田",
      plant: "种植",
      harvestReady: "可收获",
      plantSuccess: "种植成功",
      plantFail: "种植失败",
      harvestSuccess: "收获成功",
      harvestFail: "收获失败",
      build: "建造",
      upgrade: "升级",
      maxLevel: "满级",
      locked: "🔒 锁定",
    },
    town: {
      title: "城镇",
      townLevel: (n: number) => `城镇等级: ${n}`,
      operateSuccess: "操作成功",
      operateFail: "操作失败",
      npcLeft: "NPC已离开",
      campMembers: "营地成员",
      sendAway: "送别",
      gambleMerchant: "废土商人 — 血岩碎片定向赌博",
      gamble: "赌博",
      bloodShards: "血岩碎片:",
      shardPerKill: "每击杀1级敌人获得2碎片",
      knownTravelers: "已知旅人",
      reqTownLevel: "需城镇等级",
      reqDungeon: "需通关副本",
      noVisitors: "暂时没有旅人路过…",
      attractHint: "继续建造家园建筑，达到等级5后会吸引NPC来访",
      attractHint2: "城镇已经吸引了一些旅人，他们偶尔会路过这里",
    },
    talents: {
      title: "天赋树",
      available: "可用",
      used: "已用",
      remaining: "剩余",
      reset: "重置",
      unlocked: "已解锁",
      canUnlock: "可解锁",
      unlockSuccess: "天赋解锁成功",
      unlockFail: "解锁失败",
      resetSuccess: "天赋点已重置",
      resetFail: "重置失败",
      resetConfirm: "确定重置所有天赋点？此操作不可撤销。",
      styleMelee: "近战",
      styleRanged: "远程",
      styleMagic: "能量",
      centerUnlock: (skill: string) => `${skill}技能达到15级自动解锁中心点`,
    },
    gems: {
      title: "宝石",
      inventory: "宝石库存",
      empty: "暂无宝石",
      emptyHint: "采矿或击败敌人可获得宝石！",
      socket: "镶嵌",
      equippedItems: "已装备物品",
      selectGem: "选择要镶嵌的宝石：",
      noGems: "你没有宝石。去采矿或战斗吧！",
      allFilled: "所有宝石孔已填满！",
      noItems: "暂无可镶嵌物品。击败敌人或制作/掉落精良+物品可获得宝石孔。",
      dropGuide: "宝石掉落指南",
      synth: "宝石合成",
      synthRule: "5粒同品质→1粒高一级(100%) · 3粒25% · 4粒50% · 消耗金币",
      synthSuccess: "合成成功",
      combatDrop: "⚔️ 战斗",
      miningDrop: "⛏️ 采矿",
    },
    crafting: {
      smithing: "锻造",
      leatherworking: "皮革制作",
      jewelcrafting: "珠宝制作",
      cooking: "烹饪",
      alchemy: "炼金",
      prayer: "祷言",
      activeCraft: (name: string) => `正在制作 ${name}`,
      stop: "停止",
      recipe: "配方",
      crafting_: "制作中...",
      reqSmithingLevel: "需要锻造等级",
      craft: "制作",
      levelSuffix: (n: number) => `${n}级`,
      available: "可用兽皮",
      materials: "材料:",
      owned: "拥有:",
      ownLabel: "持有",
      making: "制作材料",
      craftComplete: "制作完成",
      craftFail: "制作失败",
      notEnough: "材料不足",
      // Cooking
      cookingComplete: "烹饪完成",
      cookingFail: "烹饪失败",
      // Alchemy
      alchemyComplete: "炼金完成",
      alchemyFail: "炼金失败",
      // Prayer
      bones: "骨头:",
      dragonBones: "龙骨:",
    },
    inventory: {
      title: "背包",
      equipment: "装备",
      totalStats: "总属性",
      basicCombat: "基础战斗",
      crit: "暴击",
      damageAmp: "伤害增幅",
      survival: "生存与回复",
      special: "特殊属性",
      equipped: "已装备",
      empty: "暂无物品",
      emptyHint: "击败敌人以获取战利品！",
      export_: "导出",
      import_: "导入",
      gathering: "采集类",
      combat: "战斗类",
      expand: "扩容",
      sell: "出售",
      noCombatRes: "暂无战斗资源",
      smithedItems: "已制作装备",
      equip: "装备",
      filter: {
        keepAll: "保留全部",
        magicPlus: "能量+",
        rarePlus: "稀有+",
        sacredPlus: "军用+",
        legendaryPlus: "史诗+",
        mythicOnly: "仅传说",
      } as Record<string, string>,
      disenchant: {
        common: "普通 →5瓶盖",
        magic: "能量 →10瓶盖",
        rare: "稀有 →25瓶盖",
        sacred: "军用 →60瓶盖",
        legendary: "史诗 →150瓶盖",
        mythic: "传说 →400瓶盖",
      } as Record<string, string>,
    },
  },
} as const;

export type UIText = typeof uiText;
