import { pgTable, text, serial, integer, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const gameStates = pgTable("game_states", {
  id: serial("id").primaryKey(),
  activeAction: text("active_action").notNull().default("idle"),
  actionUpdatedAt: timestamp("action_updated_at").notNull().defaultNow(),

  woodcuttingXp: integer("woodcutting_xp").notNull().default(0),
  miningXp: integer("mining_xp").notNull().default(0),
  smeltingXp: integer("smelting_xp").notNull().default(0),
  fishingXp: integer("fishing_xp").notNull().default(0),
  huntingXp: integer("hunting_xp").notNull().default(0),
  craftingXp: integer("crafting_xp").notNull().default(0),
  cookingXp: integer("cooking_xp").notNull().default(0),

  attackXp: integer("attack_xp").notNull().default(0),
  strengthXp: integer("strength_xp").notNull().default(0),
  defenceXp: integer("defence_xp").notNull().default(0),
  hitpointsXp: integer("hitpoints_xp").notNull().default(0),
  smithingXp: integer("smithing_xp").notNull().default(0),
  leatherworkingXp: integer("leatherworking_xp").notNull().default(0),
  jewelcraftingXp: integer("jewelcrafting_xp").notNull().default(0),
  thievingXp: integer("thieving_xp").notNull().default(0),
  agilityXp: integer("agility_xp").notNull().default(0),
  rangedXp: integer("ranged_xp").notNull().default(0),
  magicXp: integer("magic_xp").notNull().default(0),

  playerHp: integer("player_hp").notNull().default(-1),
  enemyHp: integer("enemy_hp").notNull().default(-1),

  gold: integer("gold").notNull().default(150),
  bloodShards: integer("blood_shards").notNull().default(0),
  bones: integer("bones").notNull().default(0),
  dragonBones: integer("dragon_bones").notNull().default(0),

  // equipment: {slot: GameItem} full item object per slot
  equipment: text("equipment").notNull().default("{}"),
  // craftItems: {itemId: qty} for smithed items
  craftItems: text("craft_items").notNull().default("{}"),
  // lootBag: GameItem[] for randomly dropped items
  lootBag: text("loot_bag").notNull().default("[]"),
  // gems: {gemKey: qty} gem inventory
  gems: text("gems").notNull().default("{}"),
  // lootFilter: minimum rarity to keep (items below are auto-disenchanted for gold)
  lootFilter: text("loot_filter").notNull().default("common"),
  // dungeonStats: { [dungeonId]: { clears, fastestSec } }
  dungeonStats: text("dungeon_stats").notNull().default("{}"),
  // equipped tool: { id, name, emoji, skill, timeMult }
  tool: text("tool").notNull().default("{}"),
  // talents: { melee: [nodeId,...], ranged: [...], magic: [...] }
  talents: text("talents").notNull().default("{}"),
  speedMult: integer("speed_mult").notNull().default(1),
  towerFloor: integer("tower_floor").notNull().default(0),
  towerKey: integer("tower_key").notNull().default(0),
  trialKey: integer("trial_key").notNull().default(0),
  trialBuffs: text("trial_buffs").notNull().default("[]"),
  trialCurses: text("trial_curses").notNull().default("[]"),
  synthesisXp: integer("synthesis_xp").notNull().default(0),
  worldTier: integer("world_tier").notNull().default(1),
  tierBossKilled: text("tier_boss_killed").notNull().default('[]'),
  extractedPowers: text("extracted_powers").notNull().default('[]'),
  activePowers: text("active_powers").notNull().default('["","",""]'),
  lootBagSize: integer("loot_bag_size").notNull().default(50),
  homestead: text("homestead").notNull().default("{}"),
  temperature: integer("temperature").notNull().default(80),
  fuelEndsAt: timestamp("fuel_ends_at"),
  stone: integer("stone").notNull().default(50),
  wood: integer("wood").notNull().default(50),
  achievements: text("achievements").notNull().default("{}"),
  pets: text("pets").notNull().default("[]"),
  foods: text("foods").notNull().default("{}"),
  potions: text("potions").notNull().default("{}"),
  herbs: text("herbs").notNull().default("{}"),
  berries: text("berries").notNull().default("{}"),
  farms: text("farms").notNull().default("{}"),
  companions: text("companions").notNull().default("[]"),
  outposts: text("outposts").notNull().default("[]"),
  npcEncounter: text("npc_encounter"),
  mastery: text("mastery").notNull().default("{}"),
  explorationXp: integer("exploration_xp").notNull().default(0),
  activeBuffs: text("active_buffs").notNull().default("[]"),
  equippedSkill: text("equipped_skill").notNull().default(""),
  activePrayer: text("active_prayer").notNull().default(""),
  prayerXp: integer("prayer_xp").notNull().default(0),
  prayerStartedAt: timestamp("prayer_started_at"),
  slayerTask: text("slayer_task"),
  slayerStreak: integer("slayer_streak").notNull().default(0),
  enemyQty: integer("enemy_qty").notNull().default(1),

  wood_0: integer("wood_0").notNull().default(0),
  wood_1: integer("wood_1").notNull().default(0),
  wood_2: integer("wood_2").notNull().default(0),
  wood_3: integer("wood_3").notNull().default(0),
  wood_4: integer("wood_4").notNull().default(0),
  wood_5: integer("wood_5").notNull().default(0),
  wood_6: integer("wood_6").notNull().default(0),
  wood_7: integer("wood_7").notNull().default(0),
  wood_8: integer("wood_8").notNull().default(0),
  wood_9: integer("wood_9").notNull().default(0),

  ore_0: integer("ore_0").notNull().default(0),
  ore_1: integer("ore_1").notNull().default(0),
  ore_2: integer("ore_2").notNull().default(0),
  ore_3: integer("ore_3").notNull().default(0),
  ore_4: integer("ore_4").notNull().default(0),
  ore_5: integer("ore_5").notNull().default(0),
  ore_6: integer("ore_6").notNull().default(0),
  ore_7: integer("ore_7").notNull().default(0),
  ore_8: integer("ore_8").notNull().default(0),
  ore_9: integer("ore_9").notNull().default(0),

  bar_0: integer("bar_0").notNull().default(0),
  bar_1: integer("bar_1").notNull().default(0),
  bar_2: integer("bar_2").notNull().default(0),
  bar_3: integer("bar_3").notNull().default(0),
  bar_4: integer("bar_4").notNull().default(0),
  bar_5: integer("bar_5").notNull().default(0),
  bar_6: integer("bar_6").notNull().default(0),
  bar_7: integer("bar_7").notNull().default(0),
  bar_8: integer("bar_8").notNull().default(0),
  bar_9: integer("bar_9").notNull().default(0),

  fish_0: integer("fish_0").notNull().default(0),
  fish_1: integer("fish_1").notNull().default(0),
  fish_2: integer("fish_2").notNull().default(0),
  fish_3: integer("fish_3").notNull().default(0),
  fish_4: integer("fish_4").notNull().default(0),
  fish_5: integer("fish_5").notNull().default(0),
  fish_6: integer("fish_6").notNull().default(0),
  fish_7: integer("fish_7").notNull().default(0),
  fish_8: integer("fish_8").notNull().default(0),
  fish_9: integer("fish_9").notNull().default(0),

  hide_0: integer("hide_0").notNull().default(0),
  hide_1: integer("hide_1").notNull().default(0),
  hide_2: integer("hide_2").notNull().default(0),
  hide_3: integer("hide_3").notNull().default(0),
  hide_4: integer("hide_4").notNull().default(0),
  hide_5: integer("hide_5").notNull().default(0),
  hide_6: integer("hide_6").notNull().default(0),
  hide_7: integer("hide_7").notNull().default(0),
  hide_8: integer("hide_8").notNull().default(0),
  hide_9: integer("hide_9").notNull().default(0),

  item_0: integer("item_0").notNull().default(0),
  item_1: integer("item_1").notNull().default(0),
  item_2: integer("item_2").notNull().default(0),
  item_3: integer("item_3").notNull().default(0),
  item_4: integer("item_4").notNull().default(0),
  item_5: integer("item_5").notNull().default(0),
  item_6: integer("item_6").notNull().default(0),
  item_7: integer("item_7").notNull().default(0),
  item_8: integer("item_8").notNull().default(0),
  item_9: integer("item_9").notNull().default(0),
  meat_0: integer("meat_0").notNull().default(0),
  meat_1: integer("meat_1").notNull().default(0),
  meat_2: integer("meat_2").notNull().default(0),
  meat_3: integer("meat_3").notNull().default(0),
  meat_4: integer("meat_4").notNull().default(0),
  meat_5: integer("meat_5").notNull().default(0),
  meat_6: integer("meat_6").notNull().default(0),
  meat_7: integer("meat_7").notNull().default(0),
  meat_8: integer("meat_8").notNull().default(0),
  meat_9: integer("meat_9").notNull().default(0),
  resourceStore: text("resource_store").notNull().default("{}"),
  playerId: text("player_id"),
});

export const insertGameStateSchema = createInsertSchema(gameStates).omit({ id: true });
export type GameState = typeof gameStates.$inferSelect;
export type InsertGameState = z.infer<typeof insertGameStateSchema>;

/** Extended state with runtime-access fields beyond Drizzle schema */
export type GameStateExt = GameState & Record<string, unknown>;
